# The set of languages for which implicit dependencies are needed:
SET(CMAKE_DEPENDS_LANGUAGES
  "C"
  "CXX"
  )
# The set of files for implicit dependencies of each language:
SET(CMAKE_DEPENDS_CHECK_C
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/ConvertUTF/ConvertUTF.c" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/ConvertUTF/ConvertUTF.c.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/unzip/ioapi.c" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/unzip/ioapi.c.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/unzip/unzip.c" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/unzip/unzip.c.o"
  )
SET(CMAKE_C_COMPILER_ID "GNU")
SET(CMAKE_DEPENDS_CHECK_CXX
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/3DSConverter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/3DSConverter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/3DSExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/3DSExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/3DSLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/3DSLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ACLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ACLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ASELoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ASELoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ASEParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ASEParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/AssbinExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/AssbinExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/AssbinLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/AssbinLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Assimp.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Assimp.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/AssimpCExport.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/AssimpCExport.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/AssimpPCH.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/AssimpPCH.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/AssxmlExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/AssxmlExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/B3DImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/B3DImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BVHLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BVHLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BaseImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BaseImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BaseProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BaseProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Bitmap.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Bitmap.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderBMesh.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderBMesh.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderDNA.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderDNA.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderModifier.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderModifier.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderScene.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderScene.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BlenderTessellator.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/BlenderTessellator.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/COBLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/COBLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CSMLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/CSMLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CalcTangentsProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/CalcTangentsProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ColladaExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ColladaExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ColladaLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ColladaLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ColladaParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ColladaParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ComputeUVMappingProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ComputeUVMappingProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ConvertToLHProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ConvertToLHProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/DXFLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/DXFLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/DeboneProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/DeboneProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/DefaultIOStream.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/DefaultIOStream.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/DefaultIOSystem.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/DefaultIOSystem.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/DefaultLogger.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/DefaultLogger.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Exporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Exporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXAnimation.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXAnimation.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXBinaryTokenizer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXBinaryTokenizer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXConverter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXConverter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXDeformer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXDeformer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXDocument.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXDocument.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXDocumentUtil.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXDocumentUtil.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXMaterial.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXMaterial.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXMeshGeometry.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXMeshGeometry.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXModel.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXModel.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXNodeAttribute.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXNodeAttribute.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXProperties.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXProperties.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXTokenizer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXTokenizer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FBXUtil.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FBXUtil.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FindDegenerates.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FindDegenerates.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FindInstancesProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FindInstancesProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FindInvalidDataProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FindInvalidDataProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/FixNormalsStep.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/FixNormalsStep.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/GenFaceNormalsProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/GenFaceNormalsProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/GenVertexNormalsProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/GenVertexNormalsProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/HMPLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/HMPLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCBoolean.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCBoolean.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCCurve.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCCurve.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCGeometry.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCGeometry.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCMaterial.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCMaterial.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCOpenings.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCOpenings.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCProfile.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCProfile.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCReaderGen.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCReaderGen.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IFCUtil.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IFCUtil.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IRRLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IRRLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IRRMeshLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IRRMeshLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/IRRShared.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/IRRShared.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Importer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Importer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ImporterRegistry.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ImporterRegistry.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ImproveCacheLocality.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ImproveCacheLocality.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/JoinVerticesProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/JoinVerticesProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LWOAnimation.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LWOAnimation.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LWOBLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LWOBLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LWOLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LWOLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LWOMaterial.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LWOMaterial.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LWSLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LWSLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/LimitBoneWeightsProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/LimitBoneWeightsProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MD2Loader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MD2Loader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MD3Loader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MD3Loader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MD5Loader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MD5Loader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MD5Parser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MD5Parser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MDCLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MDCLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MDLLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MDLLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MDLMaterialLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MDLMaterialLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MS3DLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MS3DLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MakeVerboseFormat.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MakeVerboseFormat.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/MaterialSystem.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/MaterialSystem.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/NDOLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/NDOLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/NFFLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/NFFLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OFFLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OFFLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ObjExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ObjExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ObjFileImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ObjFileImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ObjFileMtlImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ObjFileMtlImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ObjFileParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ObjFileParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OgreBinarySerializer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OgreBinarySerializer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OgreImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OgreImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OgreMaterial.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OgreMaterial.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OgreStructs.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OgreStructs.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OgreXmlSerializer.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OgreXmlSerializer.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OptimizeGraph.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OptimizeGraph.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/OptimizeMeshes.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/OptimizeMeshes.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/PlyExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/PlyExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/PlyLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/PlyLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/PlyParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/PlyParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/PostStepRegistry.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/PostStepRegistry.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/PretransformVertices.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/PretransformVertices.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ProcessHelper.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ProcessHelper.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Q3BSPFileImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Q3BSPFileImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Q3BSPFileParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Q3BSPFileParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Q3BSPZipArchive.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Q3BSPZipArchive.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Q3DLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Q3DLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/RawLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/RawLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/RemoveComments.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/RemoveComments.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/RemoveRedundantMaterials.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/RemoveRedundantMaterials.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/RemoveVCProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/RemoveVCProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SGSpatialSort.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SGSpatialSort.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SMDLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SMDLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/STEPFileEncoding.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/STEPFileEncoding.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/STEPFileReader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/STEPFileReader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/STLExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/STLExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/STLLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/STLLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SceneCombiner.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SceneCombiner.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ScenePreprocessor.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ScenePreprocessor.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SkeletonMeshBuilder.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SkeletonMeshBuilder.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SortByPTypeProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SortByPTypeProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SpatialSort.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SpatialSort.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SplitByBoneCountProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SplitByBoneCountProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/SplitLargeMeshes.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/SplitLargeMeshes.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/StandardShapes.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/StandardShapes.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/Subdivision.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/Subdivision.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/TargetAnimation.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/TargetAnimation.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/TerragenLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/TerragenLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/TextureTransform.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/TextureTransform.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/TriangulateProcess.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/TriangulateProcess.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/UnrealLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/UnrealLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/ValidateDataStructure.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/ValidateDataStructure.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/VertexTriangleAdjacency.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/VertexTriangleAdjacency.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/XFileExporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/XFileExporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/XFileImporter.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/XFileImporter.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/XFileParser.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/XFileParser.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/XGLLoader.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/XGLLoader.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/clipper/clipper.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/clipper/clipper.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/irrXML/irrXML.cpp" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/irrXML/irrXML.cpp.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/poly2tri/poly2tri/common/shapes.cc" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/common/shapes.cc.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/poly2tri/poly2tri/sweep/advancing_front.cc" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/advancing_front.cc.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/poly2tri/poly2tri/sweep/cdt.cc" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/cdt.cc.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/poly2tri/poly2tri/sweep/sweep.cc" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/sweep.cc.o"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/contrib/poly2tri/poly2tri/sweep/sweep_context.cc" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/sweep_context.cc.o"
  )
SET(CMAKE_CXX_COMPILER_ID "GNU")

# Preprocessor definitions for this target.
SET(CMAKE_TARGET_DEFINITIONS
  "ASSIMP_BUILD_BOOST_WORKAROUND"
  "ASSIMP_BUILD_NO_OWN_ZLIB"
  "ASSIMP_BUILD_DLL_EXPORT"
  )

# Pairs of files generated by the same build rule.
SET(CMAKE_MULTIPLE_OUTPUT_PAIRS
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/lib/libassimp.so" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/lib/libassimp.so.3.1.1"
  "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/lib/libassimp.so.3" "/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/lib/libassimp.so.3.1.1"
  )


# Targets to which this target links.
SET(CMAKE_TARGET_LINKED_INFO_FILES
  )

# The include file search paths:
SET(CMAKE_C_TARGET_INCLUDE_PATH
  "."
  "include"
  "code/BoostWorkaround"
  "code/../contrib/unzip"
  )
SET(CMAKE_CXX_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
SET(CMAKE_Fortran_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
SET(CMAKE_ASM_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
