# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile C with /usr/bin/gcc
# compile CXX with /usr/bin/c++
C_FLAGS = -fPIC -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/include -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BoostWorkaround -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/../contrib/unzip    -fPIC -fvisibility=hidden -Wall

C_DEFINES = -Dassimp_EXPORTS -DASSIMP_BUILD_BOOST_WORKAROUND -DASSIMP_BUILD_NO_OWN_ZLIB -DASSIMP_BUILD_DLL_EXPORT

CXX_FLAGS = -fPIC -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/include -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/BoostWorkaround -I/home/james/blender-2.71-linux-glibc211-i686/OpenCOLLADA/assimp/code/../contrib/unzip    -fPIC -fvisibility=hidden -Wall

CXX_DEFINES = -Dassimp_EXPORTS -DASSIMP_BUILD_BOOST_WORKAROUND -DASSIMP_BUILD_NO_OWN_ZLIB -DASSIMP_BUILD_DLL_EXPORT

