#pragma once

enum SHADER_ATTRIBUTE {	ATTRIBUTE_INDEX_VERTEX= 0,
			ATTRIBUTE_INDEX_COLOR,
			ATTRIBUTE_INDEX_NORMAL,
			ATTRIBUTE_INDEX_TEXTURE0,
			ATTRIBUTE_INDEX_TEXTURE1,
			ATTRIBUTE_INDEX_TEXTURE2,
			ATTRIBUTE_INDEX_TEXTURE3,
			ATTRIBUTE_INDEX_LAST
};
